### ISSUE TITLE
关于此项目clone到本地之后的运行问题

### ISSUE THREAD

**Issue by JJymsWorld** [pearmini/vast-2020#6]
你好，我是来自浙江省的一名大学生，最近在研究数据可视化的相关知识，在vast-challenge 2020中发现了您这个项目获得了奖项，所以想研究一下，但是我在clone到本地之后安装依赖之后遇到了问题，恳请您指导一下。
![image](https://user-images.githubusercontent.com/52377730/120952987-b9168680-c77e-11eb-896e-8cd40812c26b.png)
这里Time Range部分无法显示有效的数据，Frequency下面的图表也不能显示，左边sidebar中Data部分也无法添加其他的部分如g2,g3等，我没有办法定位到他的源码错误位置。我尝试了很多方法都没有得到解决，希望您能帮助指导解决，非常感谢
！

**Comment by pearmini** [comment]
看样子是数据没有正确读取，你看看[这里](https://github.com/pearmini/vast-2020/blob/90f7cf70bae2a5a70109fc4a58f8db5716642f04/src/model.js#L254)读取的 graphList 和 dc 是不是正常的。

**Comment by JJymsWorld** [comment]
感谢您的回复，按照您的指导我测试读取graphList和dc这部分数据没有错误，并且打印出的数据也都是正确的，所以问题应该不在这个地方，这个项目在您电脑上行的运行环境下依然能够正常运行的吗？

**Comment by JJymsWorld** [comment]
非常感谢您对我的问题进行了回复，问题已经解决了，我发现是依赖中webpack的问题，我是用npm管理依赖，他就会出现错误，然后我尝试使用yarn重新安装了一次依赖，他就能够正常运行了，现在问题已经解决了没有错误了。这是非常棒的一个项目，非常感谢您的指导。

**Comment by pearmini** [comment]
嗯嗯，加油
